name: Build and Test app
on: 
  push:
jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: ${{ '14.3.1' }}
      XC_PROJ: ${{ 'Koloda.xcodeproj' }}
      XC_SCHEME: ${{ 'Koloda' }}
    steps:
    - name: Select latest Xcode
      run: "sudo xcode-select -s /Applications/Xcode_$XC_VERSION.app"
    - uses: actions/checkout@v2
    - name: Run Unit and UI Tests
      run: /usr/bin/xcodebuild test -workspace "$XC_PROJ" -scheme "$XC_SCHEME" -destination 'platform=iOS Simulator,name=iPhone 11'